config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  root 'home#index'

  devise_for :users, skip: [:sessions],
             controllers: {
               registrations: 'users/registrations',
               omniauth_callbacks: 'omniauth_callbacks'
             }

  as :user do
    get '/login' => 'devise/sessions#new', as: :new_user_session
    post '/login' => 'devise/sessions#create', as: :user_session
    delete '/logout' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  namespace :events do
    get '/' => 'events#search'
    post '/' => 'events#search_result', as: :search
    get '/new' => 'events#new', as: :new
    post '/new' => 'events#create'
    get '/groupevents' => 'group_event#index', as: :group_events
    get '/groupevents/:event_id' => 'group_event#show', as: :group_event
    post '/groupevents/:event_id/register' => 'group_event#register', as: :group_event_register
    post '/groupevents/:event_id/add_relation/:user_id' => 'group_event#add_relation'
    get '/onlinechat/' => 'online_chat#index', as: :online_chat
    get '/facestofaces' => 'group_event#index', as: :face_to_faces
    get '/facestofaces/:event_id' => 'group_event#show', as: :face_to_face
    post '/facestofaces/:event_id/register' => 'group_event#register', as: :face_to_face_register
    post '/facestofaces/:event_id/add_relation/:user_id' => 'group_event#add_relation'
  end

  namespace :admin do
    get '/' => 'admin#index'

    resource :users do
      get '/' => 'users#users'
      get '/new' => 'users#new'
      post '/create' => 'users#create'
      get '/:user_id/edit' => 'users#edit'
      post '/:user_id/edit' => 'users#update'
      delete '/:user_id/delete' => 'users#delete'
    end

    resource :countries do
      get '/' => 'countries#countries'
      get '/new' => 'countries#new'
      post '/create' => 'countries#create'
      get '/:country_id/edit' => 'countries#edit'
      post '/:country_id/edit' => 'countries#update'
      delete '/:country_id/delete' => 'countries#delete'
    end

    resource :events do
      get '/' => 'events#index'
      get '/new' => 'events#new'
      post '/new' => 'events#create'
      get '/:event_id/edit' => 'events#edit'
      patch '/:event_id' => 'events#update'
      delete '/:event_id' => 'events#destroy'
    end

    resource :badges do
      get '/' => 'badges#badges'
      get '/new' => 'badges#new'
      post '/new' => 'badges#create'
      get '/:badge_id/edit' => 'badges#edit'
      patch '/:badge_id' => 'badges#update'
      delete '/:badge_id' => 'badges#delete'
    end
  end

  get '/users/:user_id/rate' => 'users/users#get_rate'
  post '/users/:user_id/rate' => 'users/users#rate'
  get '/users/:user_id' => 'users/users#show'
  post '/users/:user_id/rate' => 'users/users#rate', as: :user_rating
  get '/check_birthdate' => 'information_checker#validate_birthdate',
      as: :birthdate_validation_path
  post '/check_birthdate' => 'information_checker#check_birthdate'
  get '/change_locale/:key' => 'application#change_locale'
  post '/api/check_email/:email' => 'api#check_email',
       constraints: { email: /[0-z\.]+/ }

end

app/controllers/home_controller.rb
# Controller for HomePage
class HomeController < ApplicationController
  def index
    @modules_to_display = modules_to_display
    @achievements = current_user.achievements
    @sent_messages = current_user.sent_messages.order(created_at: :desc)[0..1]
    @received_messages = current_user.received_messages.order(created_at: :desc)[0..1]
    @event = current_user.events.order(:date).first
  end

  private

  def modules_to_display
    scores = { achievements: 3, messages: 5, event: 4 }
    scores[:messages] = 10 if @current_user.received_messages.unread.count > 0
    scores[:events] = 9 if @current_user.events.soon.count > 0
    scores[:achievements] = 6 if @current_user.achievements.recent.count > 0
    Hash[scores.sort_by { |_key, value| value }[0..2]]
  end
end

app/helpers/home_helper.rb
# Helpers for home module
module HomeHelper
end

app/views/home/index.html.erb
<body class="homepage_body">

<nav class="navbar navbar-new" role="navigation">
  <div class="container-fluid">
    <div class="collapse navbar-collapse navbar-right" id="navbar1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
            <li class="active"><%= link_to t(:home), '/', :class => 'navbar-link linkNavbar',
                            :id => 'home_link' %></li>
            <li><%= link_to t(:my_account), edit_user_registration_path, :class => 'navbar-link linkNavbar',
                            :id => 'profile_link' %></li>
            <li><%= link_to t(:events), events_path, :class => 'navbar-link linkNavbar',
                            :id => 'events_link' %></li>
            <% if current_user.admin %>
                <li><%= link_to t(:admin), '/admin', :class => 'navbar-link linkNavbar',
                                :id => 'admin_link' %></li>
            <% end %>
            <li><%= link_to t(:disconnect), destroy_user_session_path, method: :delete,
                            :class => 'navbar-link logout linkNavbar', :id => 'logout_link' %></li>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">

        <div class="dropdown">
          <button class="selector_button" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
            <div class="selector_icon"><img src="/images/flags/<%= flag(I18n.locale) %>"/></div>
            <div class="selector_text"><%= I18n.locale %></div>
          </button>

          <ul style="width: 50px !important;"  class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
            <% Country.where(available: true).each do |country| %>
                <li role="presentation" onclick="location.href = '/change_locale/<%= country.i18n_key %>'">
                  <div class="selector_line">
                    <div class="selector_nicon"><img src="/images/flags/<%= country.name %>.ico"/></div>
                    <div class="selector_ntext"><%= country.i18n_key %></div>
                    <div style="clear: both;"></div>
                  </div>
                </li>
            <% end %>
          </ul>
        </div>

      </ul>
    </div>
  </div>
</nav>

    <div id="left_module" class="module">
      <% if @modules_to_display.include?(:achievements) %>
          <%= render 'home/modules/achievements' %>
      <% end %>
    </div>
    <div id="main_module" class="module">
      <% if @modules_to_display.include?(:events) %>
          <%= render 'home/modules/events' %>
      <% end %>
    </div>
    <div id="right_top_module" class="module">
      <% if @modules_to_display.include?(:messages) %>
          <%= render 'home/modules/messages' %>
      <% end %>
    </div>
    <div id="right_bot_module" class="module">
      <%= render 'home/modules/hof' %>
    </div>
    <div id="right_bot_module2" class="module">
      <%= form_tag "/events" do %>
          <div class="home_quicksearch_field">
            <%= text_field_tag :searchterm, '', placeholder: t(:quick_search_event) %>
            <%= submit_tag t(:find), id: 'search' %>
          </div>
      <% end %>
    </div>

</body>