config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  root 'home#index'

  devise_for :users, skip: [:sessions],
             controllers: {
               registrations: 'users/registrations',
               omniauth_callbacks: 'omniauth_callbacks'
             }

  as :user do
    get '/login' => 'devise/sessions#new', as: :new_user_session
    post '/login' => 'devise/sessions#create', as: :user_session
    delete '/logout' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  namespace :events do
    get '/' => 'events#search'
    post '/' => 'events#search_result', as: :search
    get '/new' => 'events#new', as: :new
    post '/new' => 'events#create'
    get '/groupevents' => 'group_event#index', as: :group_events
    get '/groupevents/:event_id' => 'group_event#show', as: :group_event
    post '/groupevents/:event_id/register' => 'group_event#register', as: :group_event_register
    post '/groupevents/:event_id/add_relation/:user_id' => 'group_event#add_relation'
    get '/onlinechat/' => 'online_chat#index', as: :online_chat
    get '/facestofaces' => 'group_event#index', as: :face_to_faces
    get '/facestofaces/:event_id' => 'group_event#show', as: :face_to_face
    post '/facestofaces/:event_id/register' => 'group_event#register', as: :face_to_face_register
    post '/facestofaces/:event_id/add_relation/:user_id' => 'group_event#add_relation'
  end

  namespace :admin do
    get '/' => 'admin#index'

    resource :users do
      get '/' => 'users#users'
      get '/new' => 'users#new'
      post '/create' => 'users#create'
      get '/:user_id/edit' => 'users#edit'
      post '/:user_id/edit' => 'users#update'
      delete '/:user_id/delete' => 'users#delete'
    end

    resource :countries do
      get '/' => 'countries#countries'
      get '/new' => 'countries#new'
      post '/create' => 'countries#create'
      get '/:country_id/edit' => 'countries#edit'
      post '/:country_id/edit' => 'countries#update'
      delete '/:country_id/delete' => 'countries#delete'
    end

    resource :events do
      get '/' => 'events#index'
      get '/new' => 'events#new'
      post '/new' => 'events#create'
      get '/:event_id/edit' => 'events#edit'
      patch '/:event_id' => 'events#update'
      delete '/:event_id' => 'events#destroy'
    end

    resource :badges do
      get '/' => 'badges#badges'
      get '/new' => 'badges#new'
      post '/new' => 'badges#create'
      get '/:badge_id/edit' => 'badges#edit'
      patch '/:badge_id' => 'badges#update'
      delete '/:badge_id' => 'badges#delete'
    end
  end

  get '/users/:user_id/rate' => 'users/users#get_rate'
  post '/users/:user_id/rate' => 'users/users#rate'
  get '/users/:user_id' => 'users/users#show'
  post '/users/:user_id/rate' => 'users/users#rate', as: :user_rating
  get '/check_birthdate' => 'information_checker#validate_birthdate',
      as: :birthdate_validation_path
  post '/check_birthdate' => 'information_checker#check_birthdate'
  get '/change_locale/:key' => 'application#change_locale'
  post '/api/check_email/:email' => 'api#check_email',
       constraints: { email: /[0-z\.]+/ }

end

app/models/event.rb
# Class model for events
class Event < ActiveRecord::Base
  scope :face_to_face, -> { where(type: 'FaceToFace') }
  scope :group_event, -> { where(type: 'GroupEvent') }
  scope :online_chat, -> { where(type: 'OnlineChat') }
  scope :tourism_tour, -> { where(type: 'TourismTour') }
  scope :past, -> { where 'date < ?', Time.now }
  scope :future, -> { where 'date >= ?', Time.now }
  scope :soon,
        lambda {
          where('date > ? AND date <= ?', Time.now,
                Time.now + 3.days)
        }

  belongs_to :owner, class_name: 'User'
  belongs_to :address
  has_many :participations
  has_many :users, through: :participations

  validates :name, presence: true
  validates :type, presence: true
  validates :min_slots, presence: true
  validates :max_slots, presence: true
  validates :date, presence: true
  validates :end, presence: true

  accepts_nested_attributes_for :address

  def self.type
    %w(FaceToFace GroupEvent OnlineChat TourismTour)
  end

  def remaining_slots
    max_slots - users.count
  end
end

app/controllers/admin/events_controller.rb
module Admin
  # Controller for events admin panel
  class EventsController < AdminController
    before_action :actual_event, only: [:new, :edit, :update, :destroy]

    def index
      @events = Event.order(date: :desc).page(params[:page])
    end

    def new
      @event = Event.new
      @event_types =
          [
            [t(:face_to_face), 'FaceToFace'],
            [t(:group_event), 'GroupEvent'],
            [t(:tourism_tour), 'TourismTour']
          ]
      render :new_event
    end

    def create
      e = Event.new(event_params)

      if e.type != 'FaceToFace' && e.type != 'GroupEvent'
        e.type = 'GroupEvent'
      end
      if e.save
        flash[:notice] = "L'événement #{e.name} a bien été creé."
      else
        flash[:alert] = "L'événement #{e.name} n'a pas pu être créé." \
        "#{e.errors.messages}"
      end
      redirect_to action: :index
    end

    def edit
      @event_types =
          [
            [t(:face_to_face), 'FaceToFace'],
            [t(:group_event), 'GroupEvent'],
            [t(:tourism_tour), 'TourismTour']
          ]
      render :edit_event
    end

    def update
      if @event.update(event_params)
        flash[:notice] = "L'événement #{@event.name} a bien été modifié."
      else
        flash[:alert] = "L'événement #{@event.name} n'a pas pu être modifié." \
        "#{@event.errors.messages}"
      end
      redirect_to action: :index
    end

    def destroy
      name = @event.name

      if @event.destroy
        flash[:notice] = "L'événement #{name} a bien été supprimé."
      else
        flash[:alert] = "L'événement #{name} n'a pas pu être supprimé." \
        "#{@event.errors.messages}"
      end
      redirect_to action: :index
    end

    private

    def event_params
      sym = :event
      if actual_event.class == FaceToFace
        sym = :face_to_face
      elsif actual_event.class == OnlineChat
        sym = :online_chat
      elsif actual_event.class == TourismTour
        sym = :tourism_tour
      elsif actual_event.class == GroupEvent
        sym = :group_event
      end
      params.require(sym).permit(:name, :type, :min_slots,
                                 :max_slots, :date, :end)
    end

    def actual_event
      @event = Event.find(params[:event_id]) if params[:event_id]
    end
  end
end

app/controllers/events/events_controller.rb
module Events
  # Controller for Events
  class EventsController < ApplicationController
    include EventsHelper

    before_action :set_event, only: [:show, :edit, :update, :destroy]

    # GET /events
    # GET /events.json
    def search
      @event_types =
          [
            [t(:all), 'none'],
            [t(:face_to_face), 'FaceToFace'],
            [t(:tourism_tour), 'TourismTour'],
            [t(:group_event), 'GroupEvent']
          ]
    end

    def search_result
      @events = Event.where('lower(name) LIKE ?', "%#{params[:searchterm].downcase}%")
      @events = params[:past_events] == 'true' ? @events.past : @events.future
      @events = @events.where(type: params[:event_type]) if
          params[:event_type] != 'none'
      @events = @events.reject do |e|
        e.remaining_slots < params[:remaining_slots].to_i
      end if params[:remaining_slots]
    end

    # GET /events/1
    # GET /events/1.json
    def show
    end

    # GET /events/new
    def new
      @event = Event.new
      @event_types =
          [
            [t(:face_to_face), 'FaceToFace'],
            [t(:tourism_tour), 'TourismTour'],
            [t(:group_event), 'GroupEvent']
          ]
    end

    # GET /events/1/edit
    def edit
    end

    # POST /events
    # POST /events.json
    def create
      @event = Event.new(event_params)
      @address = Address.new(event_address_params)
      @event.owner_id = @current_user.id
      @event.address = @address
      if @event.type != 'FaceToFace' && @event.type != 'GroupEvent'
        @event.type = 'GroupEvent'
      end
      if @event.location == nil
        @event.location = @address.to_s
      end
      @event.users << @current_user

      if @address.save && @event.save
        badge1 = Badge.where(identifier: 'badge_maçon_name').first
        badge2 = Badge.where(identifier: 'badge_batisseur_name').first
        badge3 = Badge.where(identifier: 'badge_ironman_name').first
        if badge1 && @current_user.organized_events.count == 1
          Achievement.create(badge_id: badge1.id, user_id: @current_user.id, progression: 100)
          Notification.create(user_id: @event.owner.id, subject:'Nouveau badge !', text: "Vous avez reçu le badge \"#{badge1.name}\"")
        end
        if badge2 && @current_user.organized_events.count == 5
          Achievement.create(badge_id: badge2.id, user_id: @current_user.id, progression: 100)
          Notification.create(user_id: @event.owner.id, subject:'Nouveau badge !', text: "Vous avez reçu le badge \"#{badge2.name}\"")
        end
        if badge3 && @current_user.organized_events.count == 10
          Achievement.create(badge_id: badge3.id, user_id: @current_user.id, progression: 100)
          Notification.create(user_id: @event.owner.id, subject:'Nouveau badge !', text: "Vous avez reçu le badge \"#{badge3.name}\"")
        end
        flash[:notice] = 'Event was successfully created.'
        redirect_to event_route(@event)
      else
        redirect_to events_path, alert: @event.errors.messages
      end
    end

    # PATCH/PUT /events/1
    # PATCH/PUT /events/1.json
    def update
      if @event.update(event_params)
        redirect_to event_path(@event),
                    notice: 'Event was successfully updated.'
      else
        redirect_to event_path(@event), danger: 'Event error'
      end
    end

    # DELETE /events/1
    # DELETE /events/1.json
    def destroy
      @event.destroy
      redirect_to events_url, notice: 'Event was successfully destroyed.'
    end

    private

    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:name, :type, :min_slots,
                                    :max_slots, :date, :end,
                                    :address, :language, :desc)
    end

    def event_address_params
      params.require(:event).require(:address_attributes)
        .permit(:num, :street, :zipcode,
                :city, :country_id)
    end
  end
end

app/controllers/events/face_to_face_controller.rb
module Events
  # Controller for GroupEvent
  class FaceToFaceController < ApplicationController
    before_action :set_event, only: [:show, :edit, :update,
                                     :destroy]

    def index
      @events = Event.all
      render :search
    end

    def show
    end

    def new
    end

    def create
    end

    def edit
    end

    def update
    end

    def destroy
    end

    private

    def set_event
      @event = Event.find(params[:event_id])
    end
  end
end

app/controllers/events/group_event_controller.rb
module Events
  # Controller for online chat
  class GroupEventController < ApplicationController
    include EventsHelper

    before_action :set_event, only: [:show, :edit, :update,
                                     :destroy, :register, :add_relation]

    def index
      @past_events = current_user.events.past
      @future_events = current_user.events.future
    end

    def register
      if can_register?(@event, current_user)
        @event.users << current_user
        if @event.save
          badge1 = Badge.where(identifier: 'badge_course_name').first
          badge2 = Badge.where(identifier: 'badge_marathon_name').first
          badge3 = Badge.where(identifier: 'badge_ironman_name').first
          if badge1 && @current_user.events.count == 1
            Achievement.create(badge_id: badge1.id, user_id: @current_user.id, progression: 100)
            Notification.create(user_id: @event.owner.id, subject:'Nouveau badge !', text: "Vous avez reçu le badge \"#{badge1.name}\"")
          end
          if badge2 && @current_user.events.count == 20
            Achievement.create(badge_id: badge2.id, user_id: @current_user.id, progression: 100)
            Notification.create(user_id: @event.owner.id, subject:'Nouveau badge !', text: "Vous avez reçu le badge \"#{badge2.name}\"")
          end
          if badge3 && @current_user.events.count == 75
            Achievement.create(badge_id: badge3.id, user_id: @current_user.id, progression: 100)
            Notification.create(user_id: @event.owner.id, subject:'Nouveau badge !', text: "Vous avez reçu le badge \"#{badge3.name}\"")
          end
          Notification.create(user_id: @event.owner.id, subject:'Nouveau participant !', text: "#{@current_user.name} a rejoint votre événement \"#{@event.name}\"")
          redirect_to action: 'show', notice: 'Vous êtes maintenant inscrit à cet événement'
        else
          redirect_to action: 'show', alert: 'Une erreur est survenue lors de votre inscription.'\
          'Veuillez ressayer sous peu'
        end
      else
        redirect_to action: 'show', alert: 'Vous êtes déjà inscrit à cet événement ou celui-ci'\
        'est complet'
      end
    end

    def show
      @user_events = []
      Event.all.each do |e|
        if e.date > Time.now && (e.owner.id == @current_user.id || @current_user.events.include?(e))
          @user_events << e
        end
      end
      @user_events.sort! { |a, b| a.date <=> b.date }

      @event_users = @event.users
    end

    def add_relation
      user = User.where(id: params[:user_id].to_i).first
      if @current_user.friends.include?(user)
        redirect_to "/events/groupevents/#{@event.id}", notice: "#{user.name} fait déjà parti de vos connaissances"
      else
        @current_user.friends << user
        if @current_user.save
          Notification.create(user_id: user.id, subject: 'Nouvelle connaissance !', text: "#{@current_user.name} vous a ajouté en temps que connaissance")
          redirect_to "/events/groupevents/#{@event.id}", notice: "Vous avez bien ajouté #{user.name} à vos connaissances"
        end
      end
    end

    def edit
    end

    def update
    end

    def destroy
    end

    private

    def set_event
      @event = Event.find(params[:event_id])
    end
  end
end

app/controllers/events/online_chat_controller.rb
module Events
  # Controller for online chat
  class OnlineChatController < ApplicationController
    before_action :set_event, only: [:show, :edit, :update,
                                     :destroy]

    def index
      @events = Event.all
    end

    def show
    end

    def new
    end

    def create
    end

    def edit
    end

    def update
    end

    def destroy
    end

    private

    def set_event
      @event = Event.find(params[:event_id])
    end
  end
end

app/helpers/events_helper.rb
# Helpers for events module
module EventsHelper
  def event_route(e)
    return "/events/facestofaces/#{e.id}" if e.is_a? FaceToFace
    return "/events/groupevents/#{e.id}" if e.is_a? GroupEvent
    '/events/' if e.is_a? TourismTour
  end

  def can_register?(e, u)
    return false if e.owner_id == u.id
    return false if Time.now > e.date
    return false if e.users.include?(u)
    return false if e.max_slots == e.users.count
    true
  end
end

app/views/events/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.number_field :type %>
  </div>
  <div class="field">
    <%= f.label :min_slots %><br>
    <%= f.number_field :min_slots %>
  </div>
  <div class="field">
    <%= f.label :max_slots %><br>
    <%= f.number_field :max_slots %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :end %><br>
    <%= f.datetime_select :end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/events/edit.html.erb
<h1><%= t(:edit_event) %></h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/events/new.html.erb
<body class="eventSearch_body">
<nav class="navbar navbar-new" role="navigation">
  <div class="container-fluid">
    <div class="collapse navbar-collapse navbar-right" id="navbar1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
        <li><%= link_to t(:home), '/', :class => 'navbar-link linkNavbar',
                        :id => 'home_link' %></li>
        <li><%= link_to t(:my_account), edit_user_registration_path, :class => 'navbar-link linkNavbar',
                        :id => 'profile_link' %></li>
        <li class="active"><%= link_to t(:events), events_path, :class => 'navbar-link linkNavbar',
                                       :id => 'events_link' %></li>
        <% if current_user.admin %>
            <li><%= link_to t(:admin), '/admin', :class => 'navbar-link linkNavbar',
                            :id => 'admin_link' %></li>
        <% end %>
        <li><%= link_to t(:disconnect), destroy_user_session_path, method: :delete,
                        :class => 'navbar-link logout linkNavbar', :id => 'logout_link' %></li>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">

        <div class="dropdown">
          <button class="selector_button" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
            <div class="selector_icon"><img src="/images/flags/<%= flag(I18n.locale) %>"/></div>
            <div class="selector_text"><%= I18n.locale %></div>
          </button>

          <ul style="width: 50px !important;"  class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
            <% Country.where(available: true).each do |country| %>
                <li role="presentation" onclick="location.href = '/change_locale/<%= country.i18n_key %>'">
                  <div class="selector_line">
                    <div class="selector_nicon"><img src="/images/flags/<%= country.name %>.ico"/></div>
                    <div class="selector_ntext"><%= country.i18n_key %></div>
                    <div style="clear: both;"></div>
                  </div>
                </li>
            <% end %>
          </ul>
        </div>

      </ul>
    </div>
  </div>
</nav><br /><br />

<%= form_for @event, url: { action: :create } do |f| %>
    <table class="newEvent_table">
      <tr>
        <div class="newEvent_div">
          <h2 class="newEvent_title"><%= t(:event_title) %></h2>
          <%= f.label :name, t(:name), :class => 'eventSearch_eSlot' %><br/>
          <%= f.text_field :name, placeholder: t(:event_title) %><br/>
          <%= f.label :desc, t(:description_event), :class => 'eventSearch_eSlot' %>
          <%= f.text_area :desc %>
        </div>
      </tr><br /><br /><br />
      <tr>
        <div class="newEvent_div">
          <h2 class="newEvent_title"><%= t(:event_type) %></h2>
          <%= f.select :type, options_for_select(@event_types) %>
        </div>
      </tr><br /><br /><br />
      <tr>
        <div class="newEvent_div">
          <h2 class="newEvent_title"><%= t(:event_param) %></h2>

          <%= f.label :min_slot, t(:min_slots), :class => 'eventSearch_eSlot' %>
          <%= f.number_field :min_slots %><br />

          <%= f.label :max_slots, t(:max_slots), :class => 'eventSearch_eSlot' %>
          <%= f.number_field :max_slots %><br />

          <%= f.label :date, t(:event_date_starting), :class => 'eventSearch_eSlot' %>
          <%= f.datetime_select :date, default: 1.day.from_now %><br />

          <%= f.label :end, t(:event_date_ending), :class => 'eventSearch_eSlot' %>
          <%= f.datetime_select :end, default: 1.day.from_now + 1.minutes %><br />

          <%= f.label :language, t(:event_language), :class => 'eventSearch_eSlot' %>
          <%= f.text_field :language, placeholder: t(:event_language) %>

          <%= f.fields_for :address, Address.new do |af| %>
              <%= f.label :num, t(:event_numbers), :class => 'eventSearch_eSlot' %>
              <%= af.number_field :num %>
              <%= f.label :street, t(:event_street), :class => 'eventSearch_eSlot' %>
              <%= af.text_field :street, placeholder: t(:event_street) %>
              <%= f.label :zipcode, t(:event_code), :class => 'eventSearch_eSlot' %>
              <%= af.text_field :zipcode, placeholder: t(:event_code) %>
              <%= f.label :city, t(:event_city), :class => 'eventSearch_eSlot' %>
              <%= af.text_field :city, placeholder: t(:event_city) %>
              <%= f.label :country_id, t(:event_country), :class => 'eventSearch_eSlot' %>
              <%= af.select :country_id, Country.all.collect { |c| [c.name, c.id] } %></div>
          <% end %>

        </div>
      </tr><br /><br/>
      <tr>
        <%= submit_tag t(:create), :class => 'newEvent_button' %>
      </tr>
    </table>
<% end %>
</body>

app/views/events/events/ratings.html.erb
<body ratings_body>

</body>

app/views/events/events/search.html.erb
<body class="eventSearch_body">

<nav class="navbar navbar-new" role="navigation">
  <div class="container-fluid">
    <div class="collapse navbar-collapse navbar-right" id="navbar1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
            <li><%= link_to t(:home), '/', :class => 'navbar-link linkNavbar',
                            :id => 'home_link' %></li>
            <li><%= link_to t(:my_account), edit_user_registration_path, :class => 'navbar-link linkNavbar',
                            :id => 'profile_link' %></li>
            <li class="active"><%= link_to t(:events), events_path, :class => 'navbar-link linkNavbar',
                            :id => 'events_link' %></li>
            <% if current_user.admin %>
                <li><%= link_to t(:admin), '/admin', :class => 'navbar-link linkNavbar',
                                :id => 'admin_link' %></li>
            <% end %>
            <li><%= link_to t(:disconnect), destroy_user_session_path, method: :delete,
                            :class => 'navbar-link logout linkNavbar', :id => 'logout_link' %></li>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">

        <div class="dropdown">
          <button class="selector_button" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
            <div class="selector_icon"><img src="/images/flags/<%= flag(I18n.locale) %>"/></div>
            <div class="selector_text"><%= I18n.locale %></div>
          </button>

          <ul style="width: 50px !important;"  class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
            <% Country.where(available: true).each do |country| %>
                <li role="presentation" onclick="location.href = '/change_locale/<%= country.i18n_key %>'">
                  <div class="selector_line">
                    <div class="selector_nicon"><img src="/images/flags/<%= country.name %>.ico"/></div>
                    <div class="selector_ntext"><%= country.i18n_key %></div>
                    <div style="clear: both;"></div>
                  </div>
                </li>
            <% end %>
          </ul>
        </div>

      </ul>
    </div>
  </div>
</nav>

<%= form_tag action: :search_result do %>
    <div class="eventSearch_field" id="searchform">
      <%= text_field_tag :searchterm, '', placeholder: t(:quick_search_event) %>
      <%= submit_tag t(:find), id: 'search' %>
      <%= link_to '+', { action: :new }, class: 'new_event_button' %>
    </div>

    <button type="button" id="adv-search-btn"><%= t(:advanced_search) %></button>

    <div class="adv-search-div">
      <table class="eventSearch_table_radio">
        <tr>
          <td><div class="eventSearch_div"><%= radio_button_tag :past_events, true %>
            <%= label_tag :past_events_true, t(:past_events), :class => 'eventSearch_label' %></div></td>
          <td><div class="eventSearch_div"><%= radio_button_tag :past_events, false, checked: true %>
            <%= label_tag :past_events_false, t(:future_events), :class => 'eventSearch_label' %></div></td>
        </tr>
      </table><br />
      <table class="eventSearch_table_event">
        <tr>
          <td class="event_type_td"><%= label_tag :past_events_false, t(:event_type), :class => 'eventSearch_eType' %>
            <%= select_tag :event_type, options_for_select(@event_types) %></td>
          <td class="event_slot_td"><%= label_tag :remaining_slots, t(:remaining_slots), :class => 'eventSearch_eSlot' %>
            <%= number_field_tag :remaining_slots, 1 %></td>
          <td class="event_q_td">
            <table class="eventSearch_table_friends">
              <tr>
                <td class="event_q1_td"><%= label_tag :friends_in_yes, t(:yes_event), :class => 'eventSearch_eFriends' %>
                  <%= radio_button_tag :friends_in, 'yes' %></td>
                <td class="event_q2_td"><%= label_tag :friends_in_no, t(:no_event), :class => 'eventSearch_eFriends' %>
                  <%= radio_button_tag :friends_in, 'no' %></td>
                <td class="event_q3_td"> <%= label_tag :friends_in_whatever, t(:whatever), :class => 'eventSearch_eFriends' %>
                  <%= radio_button_tag :friends_in, 'whatever', checked: true %></td>
              </tr>
            </table>
          </td>
        </tr>
      </table><br />
    </div>

<% end %>

</body>

<%= javascript_include_tag 'application.js' %>

app/views/events/events/search_result.html.erb
<body class="eventSearchResult_body">
  <nav class="navbar navbar-new" role="navigation">
    <div class="container-fluid">
      <div class="collapse navbar-collapse navbar-right" id="navbar1">
        <ul class="nav navbar-nav">
          <li class="dropdown">
              <li><%= link_to t(:home), '/', :class => 'navbar-link linkNavbar',
                              :id => 'home_link' %></li>
              <li><%= link_to t(:my_account), edit_user_registration_path, :class => 'navbar-link linkNavbar',
                              :id => 'profile_link' %></li>
              <li class="active"><%= link_to t(:events), events_path, :class => 'navbar-link linkNavbar',
                              :id => 'events_link' %></li>
              <% if current_user.admin %>
                  <li><%= link_to t(:admin), '/admin', :class => 'navbar-link linkNavbar',
                                  :id => 'admin_link' %></li>
              <% end %>
              <li><%= link_to t(:disconnect), destroy_user_session_path, method: :delete,
                              :class => 'navbar-link logout linkNavbar', :id => 'logout_link' %></li>
          </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">

          <div class="dropdown">
            <button class="selector_button" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
              <div class="selector_icon"><img src="/images/flags/<%= flag(I18n.locale) %>"/></div>
              <div class="selector_text"><%= I18n.locale %></div>
            </button>

            <ul style="width: 50px !important;"  class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
              <% Country.where(available: true).each do |country| %>
                  <li role="presentation" onclick="location.href = '/change_locale/<%= country.i18n_key %>'">
                    <div class="selector_line">
                      <div class="selector_nicon"><img src="/images/flags/<%= country.name %>.ico"/></div>
                      <div class="selector_ntext"><%= country.i18n_key %></div>
                      <div style="clear: both;"></div>
                    </div>
                  </li>
              <% end %>
            </ul>
          </div>

        </ul>
      </div>
    </div>
  </nav>

  <div class="content">
    <div class="panel panel-info">
      <div class="panel-heading panel-color">
        <%= t(:events) %>
      </div>
      <div class="panel-body content-eventSearchResult">
        <table class="table">
          <tr>
            <th><%= t(:event_type) %></th>
            <th><%= t(:event_title) %></th>
            <th><%= t(:date_begin) %></th>
            <th><%= t(:free_slots) %></th>
          </tr>
          <% @events.each do |e| %>
              <tr>
                <td><div class="container_icon"><%= image_tag("icon_ftf.png", :alt => "event_type_icon") %></div></td>
                <td><%= link_to e.name, event_route(e) %></td>
                <td><%= e.date %></td>
                <td><%= e.max_slots - e.users.count %></td>
              </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</body>

app/views/events/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @event.type %>
</p>

<p>
  <strong>Min slots:</strong>
  <%= @event.min_slots %>
</p>

<p>
  <strong>Max slots:</strong>
  <%= @event.max_slots %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>End:</strong>
  <%= @event.end %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>